

[[language]]
name = "c"
indent = { tab-width = 2, unit = " " }
config = { "clangd.fallbackFlags" = [ "-std=23" ] }
[[language]]
name = "odin"
indent = { tab-width = 2, unit = " " }
[[language]]
name = "zig"
indent = { tab-width = 2, unit = " " }
[[language]]
name = "h"
indent = { tab-width = 2, unit = " " }
config = { "clangd.fallbackFlags" = [ "-std=2x" ] }
# language-servers = [] #[ { name = "c-lsp" } ]
# args = ["-std=gnu2x"]
#indent-style = 2
#auto-format = true
[[[language]]
name = "c++"
indent = {tab-width = 2, unit = " "}
config = { "clangd.fallbackFlags" = [ "-std=c++23" ] }
#auto-format = true
[[[language]]
name = "cpp"
indent = {tab-width = 2, unit = " "}
config = { "clangd.fallbackFlags" = [ "-std=c++23" ] }
a#uto-format = true
[[language]]
name = "python"
indent = {tab-width = 2, unit = " "}
[[language]]
name = "py"
indent = {tab-width = 2, unit = " "}
[[language]]
name = "glsl"
indent = {tab-width = 2, unit = " "}
scope = "source.glsl"
file-types = ["glsl", "vert", "tesc", "tese", "geom", "frag", "comp", "rgen", "rint", "rchit", "rmiss", "mesh", "task"]
injection-regex = "glsl"

# [lanuguage-server.c-lsp]
# command "clangd"
# args = ["-std=gnu2x"]
